apiVersion: postgresql.org/v1
kind: PostgresDatabase
metadata:
  name: app4
spec:
  dbName: db4
  dbOwner: user4
  dbRoleName: user4
  dbRolePassword: swordfish
  dbExtensions:
    - hstore
  onDeletion:
    dropDB: true
    dropRole: true
