apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgdatabases.postgresql.org
spec:
  conversion:
    strategy: None
  group: postgresql.org
  names:
    kind: PostgresDatabase
    listKind: PostgresDatabaseList
    plural: pgdatabases
    shortNames:
    - pgdb
    singular: pgdatabase
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The name of the database
      jsonPath: .spec.dbName
      name: DBNAME
      type: string
    - description: Owner of the database
      jsonPath: .spec.dbOwner
      name: DBOWNER
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
            properties:
              dbExtensions:
                items:
                  type: string
                type: array
              dbInstanceId:
                type: string
              dbName:
                type: string
              dbOwner:
                type: string
              dbRoleName:
                type: string
              dbRolePassword:
                type: string
              extraSQL:
                type: string
            required:
            - dbName
            - dbOwner
            - dbRoleName
            - dbRolePassword
    served: true
    storage: true
